-- 内容中台数据库结构(全新库的权威定义)。
-- 表按依赖顺序排列,每张表的列 / 外键 / 约束 / 索引都在各自 CREATE 处一次性写清楚。
-- 应用方式:开发阶段用 database/reset-dev.sql 整库清空后重跑本文件;已有旧库的升级步骤见 SERVER_SETUP.md。

-- ============================================================================
-- 1. 账号与登录
-- ============================================================================

-- 角色三级:超级管理员(看/管全部)/ 管理员(开发商,拥有自己的项目)/ 员工(归某管理员,只在被分配项目里干活)。
-- manager_id:员工指向其所属管理员;超管 / 管理员为 NULL(自引用外键)。
CREATE TABLE IF NOT EXISTS console_users (
  id text PRIMARY KEY,
  name text NOT NULL,
  phone text NOT NULL,
  role text NOT NULL CHECK (role IN ('超级管理员', '管理员', '员工')),
  manager_id text REFERENCES console_users(id) ON DELETE SET NULL,
  password_hash text,
  status text NOT NULL DEFAULT 'active',
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_console_users_created_at ON console_users (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_console_users_phone_unique ON console_users (phone);
CREATE INDEX IF NOT EXISTS idx_console_users_manager ON console_users (manager_id);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES console_users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions (expires_at);

-- ============================================================================
-- 2. 项目与授权(多租户核心)
-- ============================================================================

-- 每个项目归属创建它的用户(owner_id → 管理员 / 超管)。业务内容都按 property_id 挂到这里。
CREATE TABLE IF NOT EXISTS properties (
  id text PRIMARY KEY,
  owner_id text NOT NULL REFERENCES console_users(id) ON DELETE CASCADE,
  developer text NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  stage text NOT NULL,
  address text NOT NULL,
  description text NOT NULL DEFAULT '-',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_properties_created_at ON properties (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_properties_owner ON properties (owner_id, created_at DESC);

-- 员工 ↔ 项目 多对多授权:管理员把自己名下项目分配给名下员工(仅员工使用)。
CREATE TABLE IF NOT EXISTS user_project_access (
  user_id     text NOT NULL REFERENCES console_users(id) ON DELETE CASCADE,
  property_id text NOT NULL REFERENCES properties(id)    ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, property_id)
);

CREATE INDEX IF NOT EXISTS idx_upa_user     ON user_project_access (user_id);
CREATE INDEX IF NOT EXISTS idx_upa_property ON user_project_access (property_id);

-- 项目渠道:新建项目自动插一条默认渠道,详情页据此渲染二维码 / NFC 链接。
CREATE TABLE IF NOT EXISTS property_channels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  channel_type text NOT NULL CHECK (channel_type IN ('visitor','resident','agent')),
  label text NOT NULL,
  qr_value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 0,
  UNIQUE (property_id, channel_type)
);

CREATE INDEX IF NOT EXISTS idx_property_channels_property ON property_channels (property_id, sort_order);

-- ============================================================================
-- 3. 图片素材
-- ============================================================================

CREATE TABLE IF NOT EXISTS materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  title text NOT NULL,
  category text NOT NULL DEFAULT '未分类',
  platforms text[] NOT NULL DEFAULT '{}',
  size_text text NOT NULL DEFAULT '-',
  file_size_bytes integer NOT NULL DEFAULT 0,
  image_url text,
  stage text NOT NULL DEFAULT '待配置',
  tone text NOT NULL DEFAULT '-',
  uploader text NOT NULL DEFAULT '系统',
  color text NOT NULL DEFAULT '#d8dee9',
  accent text NOT NULL DEFAULT '#64748b',
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_materials_updated_at ON materials (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_uploaded_at ON materials (uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_property ON materials (property_id, updated_at DESC);

-- 原图字节单独存(1:1),随素材级联删除。
CREATE TABLE IF NOT EXISTS material_files (
  material_id integer PRIMARY KEY REFERENCES materials(id) ON DELETE CASCADE,
  original_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS material_tags (
  material_id integer NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('attribute', 'selling')),
  tag text NOT NULL,
  PRIMARY KEY (material_id, kind, tag)
);

CREATE INDEX IF NOT EXISTS idx_material_tags_kind_tag ON material_tags (kind, tag);

-- ============================================================================
-- 4. 标签 / 卖点配置(树形)
-- ============================================================================

CREATE TABLE IF NOT EXISTS config_nodes (
  id text PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  config_type text NOT NULL CHECK (config_type IN ('tag', 'selling_point')),
  parent_id text REFERENCES config_nodes(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  count integer,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_config_nodes_type_parent ON config_nodes (config_type, parent_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_config_nodes_property ON config_nodes (property_id, config_type, parent_id, sort_order);

CREATE TABLE IF NOT EXISTS config_node_modes (
  node_id text NOT NULL REFERENCES config_nodes(id) ON DELETE CASCADE,
  mode text NOT NULL,
  PRIMARY KEY (node_id, mode)
);

-- ============================================================================
-- 5. 笔记与策略看板(概览数据源)
-- ============================================================================

CREATE TABLE IF NOT EXISTS notes (
  id text PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  title text NOT NULL,
  author text NOT NULL,
  params text[] NOT NULL DEFAULT '{}',
  published_at timestamptz NOT NULL DEFAULT now(),
  likes integer NOT NULL DEFAULT 0,
  exposure_count integer NOT NULL DEFAULT 0,
  platform text NOT NULL DEFAULT 'xhs',
  content_type text NOT NULL DEFAULT 'image',
  owner_type text NOT NULL DEFAULT 'personal',
  comments integer NOT NULL DEFAULT 0,
  collects integer NOT NULL DEFAULT 0,
  shares integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_notes_published_at ON notes (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_notes_author ON notes (author);
CREATE INDEX IF NOT EXISTS idx_notes_platform_content ON notes (platform, content_type);
CREATE INDEX IF NOT EXISTS idx_notes_owner_type ON notes (owner_type);
CREATE INDEX IF NOT EXISTS idx_notes_property ON notes (property_id, published_at DESC);

CREATE TABLE IF NOT EXISTS strategy_heat_rows (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  label text NOT NULL,
  left_label text NOT NULL,
  left_width text NOT NULL,
  right_label text NOT NULL,
  right_width text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_strategy_heat_rows_property ON strategy_heat_rows (property_id, sort_order);

CREATE TABLE IF NOT EXISTS strategy_keywords (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  label text NOT NULL,
  count integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_strategy_keywords_property ON strategy_keywords (property_id, sort_order);

-- ============================================================================
-- 6. 发布存档与文案风格档案
-- ============================================================================

-- 发布存档:只存引用(material_ids 指向 materials)+ 文案 + 发布人/渠道,不复制图片字节。
CREATE TABLE IF NOT EXISTS publish_records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  material_ids integer[] NOT NULL DEFAULT '{}',
  title text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  topics text[] NOT NULL DEFAULT '{}',
  publisher text NOT NULL DEFAULT '',
  channel text NOT NULL DEFAULT 'xhs',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_publish_records_property ON publish_records (property_id, created_at DESC);

-- 每个项目一份文案风格档案(1:1):风格 spec + 认可范例,注入 AI 生成让文案风格稳定。
CREATE TABLE IF NOT EXISTS caption_profiles (
  property_id text PRIMARY KEY REFERENCES properties(id) ON DELETE CASCADE,
  style_spec  text  NOT NULL DEFAULT '',
  examples    jsonb NOT NULL DEFAULT '[]',
  constraints jsonb NOT NULL DEFAULT '{}',
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 7. 旧草稿页(遗留,逐步被公开预览 / 小程序取代)
-- ============================================================================

CREATE TABLE IF NOT EXISTS drafts (
  id text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  tags text[] NOT NULL DEFAULT '{}',
  caption text NOT NULL,
  topics text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_drafts_created_at ON drafts (created_at DESC);

CREATE TABLE IF NOT EXISTS draft_images (
  id text PRIMARY KEY,
  draft_id text NOT NULL REFERENCES drafts(id) ON DELETE CASCADE,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  selected boolean NOT NULL DEFAULT false,
  score integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (draft_id, filename)
);

CREATE INDEX IF NOT EXISTS idx_draft_images_draft ON draft_images (draft_id, sort_order);
