CREATE TABLE IF NOT EXISTS materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  category text NOT NULL DEFAULT '未分类',
  platforms text[] NOT NULL DEFAULT '{}',
  size_text text NOT NULL DEFAULT '-',
  file_size_bytes integer NOT NULL DEFAULT 0,
  image_url text,
  stage text NOT NULL DEFAULT '待配置',
  tone text NOT NULL DEFAULT '-',
  uploader text NOT NULL DEFAULT '系统',
  color text NOT NULL DEFAULT '#d8dee9',
  accent text NOT NULL DEFAULT '#64748b',
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_materials_updated_at ON materials (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_materials_uploaded_at ON materials (uploaded_at DESC);

ALTER TABLE IF EXISTS materials ADD COLUMN IF NOT EXISTS file_size_bytes integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS materials ADD COLUMN IF NOT EXISTS image_url text;

CREATE TABLE IF NOT EXISTS material_files (
  material_id integer PRIMARY KEY REFERENCES materials(id) ON DELETE CASCADE,
  original_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS material_tags (
  material_id integer NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('attribute', 'selling')),
  tag text NOT NULL,
  PRIMARY KEY (material_id, kind, tag)
);

CREATE INDEX IF NOT EXISTS idx_material_tags_kind_tag ON material_tags (kind, tag);

CREATE TABLE IF NOT EXISTS config_nodes (
  id text PRIMARY KEY,
  config_type text NOT NULL CHECK (config_type IN ('tag', 'selling_point')),
  parent_id text REFERENCES config_nodes(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  count integer,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_config_nodes_type_parent ON config_nodes (config_type, parent_id, sort_order);

CREATE TABLE IF NOT EXISTS config_node_modes (
  node_id text NOT NULL REFERENCES config_nodes(id) ON DELETE CASCADE,
  mode text NOT NULL,
  PRIMARY KEY (node_id, mode)
);

CREATE TABLE IF NOT EXISTS notes (
  id text PRIMARY KEY,
  title text NOT NULL,
  author text NOT NULL,
  params text[] NOT NULL DEFAULT '{}',
  published_at timestamptz NOT NULL DEFAULT now(),
  likes integer NOT NULL DEFAULT 0,
  exposure_count integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_notes_published_at ON notes (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_notes_author ON notes (author);

ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'xhs';
ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS content_type text NOT NULL DEFAULT 'image';
ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS owner_type text NOT NULL DEFAULT 'personal';
ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS comments integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS collects integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS notes ADD COLUMN IF NOT EXISTS shares integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_notes_platform_content ON notes (platform, content_type);
CREATE INDEX IF NOT EXISTS idx_notes_owner_type ON notes (owner_type);

CREATE TABLE IF NOT EXISTS strategy_heat_rows (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  left_label text NOT NULL,
  left_width text NOT NULL,
  right_label text NOT NULL,
  right_width text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS strategy_keywords (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  count integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS properties (
  id text PRIMARY KEY,
  developer text NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  stage text NOT NULL,
  address text NOT NULL,
  description text NOT NULL DEFAULT '-',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_properties_created_at ON properties (created_at DESC);

CREATE TABLE IF NOT EXISTS property_channels (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id text NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  label text NOT NULL,
  qr_value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_property_channels_property ON property_channels (property_id, sort_order);

CREATE TABLE IF NOT EXISTS console_users (
  id text PRIMARY KEY,
  name text NOT NULL,
  phone text NOT NULL,
  role text NOT NULL,
  property text NOT NULL,
  password_hash text,
  status text NOT NULL DEFAULT 'active',
  last_login_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_console_users_created_at ON console_users (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_console_users_phone ON console_users (phone);
CREATE UNIQUE INDEX IF NOT EXISTS idx_console_users_phone_unique ON console_users (phone);

ALTER TABLE IF EXISTS console_users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE IF EXISTS console_users ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE IF EXISTS console_users ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

CREATE TABLE IF NOT EXISTS auth_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES console_users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS drafts (
  id text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  tags text[] NOT NULL DEFAULT '{}',
  caption text NOT NULL,
  topics text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_drafts_created_at ON drafts (created_at DESC);

CREATE TABLE IF NOT EXISTS draft_images (
  id text PRIMARY KEY,
  draft_id text NOT NULL REFERENCES drafts(id) ON DELETE CASCADE,
  filename text NOT NULL,
  original_name text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  selected boolean NOT NULL DEFAULT false,
  score integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  bytes bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (draft_id, filename)
);

CREATE INDEX IF NOT EXISTS idx_draft_images_draft ON draft_images (draft_id, sort_order);
